config/routes.rb
Rails.application.routes.draw do
  root 'homes#index'

  resource :users, controller: 'registrations', only: [:create, :edit, :update] do
    get '/sign_up', action: 'new'
  end

  resource :users, controller: 'sessions', only: [] do
    get '/sign_in', action: 'new'
    post '/sign_in', action: 'create'
    delete '/sign_out', action: 'destroy'
  end

  resource :carts, controller: 'carts', only: [] do
    get '/my_cart', action: 'show'
    post '/add_to_cart', action: 'create'
  end

  resource :favorites, controller: 'favorites', only: [] do
    get '/my_fav_products', action: 'show'
    post '/add_fav_products', action: 'create'
  end

  resource :orders, controller: 'orders', only:[] do
    get '/my_orders', action: 'index'
    get '/my_order_detail', action: 'show'
    post '/create_order', action: 'create'
  end
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :products
  has_many :items, class_name: "CartItem"
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :cart
  belongs_to :order
  belongs_to :product
end

app/models/fav_product.rb
class FavProduct < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :cart_items
  has_many :items, class_name: "CartItem"
end

app/models/product.rb
class Product < ApplicationRecord
  has_one :stock
  has_many :fav_products
  has_many :user, through: :fav_products
end

app/models/stock.rb
class Stock < ApplicationRecord
  belongs_to :product
end

app/models/user.rb
class User < ApplicationRecord
  before_create :encrypt_password

  has_one :cart
  has_one :orders
  has_many :fav_products
  has_many :products, through: :fav_products

  validates :email, presence: true, uniqueness: true, format: { with: /[\w]+@([\w-]+\.)+[\w-]{2,4}/ }
  validates :password, presence: true, confirmation: true, length: { minimum: 4 }
  validates :nickname, presence: true

  def self.login(user)
    pw = Digest::SHA1.hexdigest("a#{user[:password]}Z")
    User.find_by(email: user[:email], password: pw)
  end

  private
    def encrypt_password
      self.password = Digest::SHA1.hexdigest("a#{self.password}Z")
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper

  private
  def session_required
    redirect_to sign_in_users_path, notice: '請先登入會員' unless user_signed_in?
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :session_required
  before_action :find_cart, only: :show
  before_action :find_product, only: :create
  before_action :current_cart, only: :create

  def show; end

  def create
    # stock = (@product.stock.value - cart_params[:number].to_i)
    # @product.stock.update(value: stock)
    @stock.update(value: @stock.value - cart_params[:number].to_i)
    @cart.items.create(product_id: @product.id, quantity: cart_params[:number])
  end

  private

    def find_cart
      @cart = current_user.cart || current_user.build_cart
      # @cart = Cart.find_by(id: params[:id])
    end

    # def find_product
    #   @product = Product.find_by(id: params[:product_id])
    # end

    def find_stock
      @stock = Stock.find_by!(product_id: params[:product_id])
    end

    def current_cart
      @cart ||= Cart.first_or_create(user_id: current_user.id)
    end

    # params = { 'number' => 2 }
    def cart_params
      params.permit(:number)
    end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  before_action :session_required

  def index
    @products = current_user.fav_products
  end

  def create
    current_user.fav_products.create(product_id: params[:id], note: note_params[:note])
    @note = note_params[:note]
  end

  private

    def note_params
      params.permit(:note)
    end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :session_required
  before_action :find_cart, only: :create

  def index
    @orders = current_user.orders
  end

  def show
    @order = Order.find_by(id: params[:order_id])
  end

  def create
    @order = current_user.create_order(
      items: @cart.items,
      email: current_user.email
    )
  end

  private

    def find_cart
      @cart = Cart.find_by(id: params[:id])
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  before_action :session_required, only: [:edit, :update]
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path, notice:'註冊成功'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path, notice: '資料更新成功'
    else
      render :edit
    end
  end


  private

    def user_params
      params.require(:user).permit(:email, :password, :password_confirmation, :nickname)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    @user = User.new
  end

  def create
    user = User.login(params[:user])
    if user
      session[:user9527] = user.id
      redirect_to root_path, notice:'登入成功'
    else
      redirect_to sign_in_users_path, notice: '登入失敗!'
    end
  end
  
  def destroy
    session[:user9527] = nil
    redirect_to root_path, notice: '已登出!'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    if session[:user9527].present?
      @_user9527 ||= User.find_by(id: session[:user9527])
    else
      nil
    end
  end

  def user_signed_in?
    if current_user
      return true
    else
      return false
    end
  end
end

app/views/carts/create.html.slim
div Success!

app/views/carts/show.html.slim
@cart.cart_items.find_each do |item|
  table
    tr
      td=item.name
      td=item.stock.value

app/views/favorites/create.html.slim
div
  b
    | Success!
  | note:
  = @note 

app/views/favorites/show.html.slim
@products.find_each do |product|
  table
    tr
      td = product.name
      td = "Note: <br> #{product.note}".html_safe

app/views/homes/index.html.erb
<h1>首頁</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Interview</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "shared/navbar" %>
    <%= render "shared/flash" if notice %>
    <%= yield %>
  </body>
</html>

app/views/orders/create.html.slim
div Success!

app/views/orders/index.html.slim
@orders.find_each do |order|
  table
    tr
      td=order.id
      td=order.create_at

app/views/orders/show.html.slim
table
  tr
    td=@order.id
    td=@order.email

@order.items.map do |item|
  table
    tr
      td=item.name
      td=item.quantity

app/views/shared/_flash.html.erb
<p><%= notice %></p>

app/views/shared/_navbar.html.erb
<nav>
  <ul>
    <li><%= link_to "首頁", root_path %></li>
  </ul>
  <ul>
    <% if current_user %>
      <li><%= current_user.nickname %></li>
      <li><%= link_to "登出", sign_out_users_path, method: 'delete' %></li>
      <li><%= link_to "編輯會員資料", edit_users_path %></li>
    <% else %>
      <li><%= link_to "註冊", sign_up_users_path %></li>
      <li><%= link_to "登入", sign_in_users_path %></li>
    <% end %>
  </ul>
</nav>